steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/alpine-canto-277206/first_app', '.'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/alpine-canto-277206/first_app'] 
